### ISSUE TITLE
Elementskit Header & Footer Builder - samples will not be inserted

### ISSUE THREAD

**Issue by amelsens** [xpeedstudio/elementskit#1]
Hello,
I want to insert a sample of the headers in the Header & Footer Builder but elementor turning in a loop. The sample is not inserted.
I use it to test on a Windows 10 Pro IIS localhost delopement platform.
It seems that there is maybe an external non PHP script that is being used, as Jason of something else to insert the samples?
Or what could be the reason why this is not working?
Thanks for any help.
Best Regards.

**Comment by xperter** [comment]
Can we look into the sample you're trying to insert?

**Comment by amelsens** [comment]
Hello,
I can sent you here some screencapture images to see what I mean:
![Elementskit-Lte-Step5-Insert-Loading-Hanging](https://user-images.githubusercontent.com/10380856/61740344-b4b17200-ad8e-11e9-8bbe-bea16c5b126e.jpg)
![Elementskit-Lte-Step4](https://user-images.githubusercontent.com/10380856/61740345-b4b17200-ad8e-11e9-8c0b-721299bc50ce.jpg)
![Elementskit-Lte-Step3](https://user-images.githubusercontent.com/10380856/61740346-b4b17200-ad8e-11e9-8f21-a48cf38ea425.jpg)
![Elementskit-Lte-Step2](https://user-images.githubusercontent.com/10380856/61740347-b4b17200-ad8e-11e9-92fb-273a2def61fc.png)
![Elementskit-Lte-Step1](https://user-images.githubusercontent.com/10380856/61740348-b4b17200-ad8e-11e9-82d8-d436299afc47.jpg)
In fact, at screen Step5, that's the point where I try to insert a sample of an prebuild header but Elementor at this point is hanging The sample will not be inserted. It seems it's hanging, nothing is happening from this point.
It's the same issue for any sample I choose. The procedure to insert is not working as expected. It's always hanging.
I have got something like this issue with an other Wordpress plugin before and the reason was that the script interpreter Jason was not installend on the IIS Webserver. Now it's working.
Maybe the Insert procedure uses also some special scripts...?
I have already did the new upgrade of Elementskit but I get the same issue.
I hope that you hve enough with my screencapture images...
As I worte before, at this moment I'm using a localhost test environment on Windows O.S.
Normaly, I can use all WordPress themes and plugins and IIS webserver is almost completly compatible with all recent PHP and mySQL scripts.
Thanks in advance to help me furtheron.
Best Regards.

**Comment by xperter** [comment]
We need the error log to investigate it. Can you put the following code to your wp-config.php file? it will generate errors and write them to a debug.log file (located at wp-content).
`define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);`

After that please do the following steps:
Clear the log file, 
Then try to import layouts as usual, 
Check the log file, it should have some logs in it now. 
Post the log here.


ref:
https://snapcreek.com/blog/wordpress-error-log-friend/
https://wordpress.org/support/article/debugging-in-wordpress/

**Comment by amelsens** [comment]
Hello,
Ok, I have a debug.log file. See it in attachment.
[debug.log](https://github.com/xpeedstudio/elementskit/files/3426928/debug.log)
I hope this can help you to trace the issue...
Best Regards.

**Comment by amelsens** [comment]
Hi,
I want to tell you also that I have deactivated all other Wordpress plugins, except Elementor (Free edition) and of cause Elementskit Lite. But this solved nothing.
And I use temporarly the Twenty Nineteen theme.
In fact, which theme is the best to use it with Elementskit Lite? I didn't found anything about the best theme to use with Elementskit Lite.
Thanks in advanced.
Best Regards.

**Comment by xperter** [comment]
Found the issue, in \wp-content\plugins\elementskit-lite\modules\library\manager\api.php file, all `ELementor` should be renamed to `Elementor` 
We will update the plugin to wordpress.org by today.

**Comment by amelsens** [comment]
Hi,
Ok, thank you very much.
I'm looking forward to the update and will keep you informed about it.
Best Regards.

**Comment by amelsens** [comment]
Hi,
YES!!! It's working! ;) I have installed the upgrade and it's working.
Thank you so much to resolve this issue.
I have another little question, because I didn' found anything else about it in the documentation.
Witch is the prefered Wordpress theme to use with the Elementskit Header & Footer builder?
I quess it should be one that have good support for Elementor?
Will you give me the name of a good and fast Wordpress theme to work with or give me some references where I can find some good Wordpress themes who are compatible with your Elementskit Lite plugin.
Thank you so much.
Best Regards.

**Comment by xperter** [comment]
We've tested it with the following themes from wordpress.org so far:
`Astra
oceanWP 
bb-theme 
genesis 
generatePress 
Futurio
hestia
neve
Hello elementor
Materialis
Orfeo`

And if you are looking for a premium theme, u can take a look at our portfolio: https://themeforest.net/user/xpeedstudio/portfolio

**Comment by amelsens** [comment]
Hi,
Ok, thank you so much for your fast and great support!
You're much better and faster than some other very expensive webdevelopment tools.
I appreciate it. I will write a litte review on the WordPress.org plugin directory.
Again, many thanks and Best Regards.
