### ISSUE TITLE
Parent menu items weblinks not working in Edit Nav menu in Header Builder

### ISSUE THREAD

**Issue by amelsens** [xpeedstudio/elementskit#2]
![Elementskit-Lte-Parent-Menu-item-no-weblink](https://user-images.githubusercontent.com/10380856/62008936-1b50da00-b159-11e9-97d9-858f54cacff2.jpg)
Hello,
I have discoverd that the parent menu items weblinks are not working at live state.
Because it seems to work in the Customizer (via Admin menu > Appreance > Custimize).
So, I think that is not a normal behaviour of the Edit Nav menu Elementor widget.
See also the screencapture in attachment to show you what I mean by the parent menu items. This is the menu item that hold also a sub menu. 
I have try it with different themes but it's still the same issue.
Thanks in advance to look at it.
Best Regards.

**Comment by xperter** [comment]
Most probably, that HOME menu doesn't have any valid link or has a hash (#) link in it. 
Can you please recheck the link you inerted? and it will be easier to diagnose the issue if you can provide a live page url with the issue.

**Comment by amelsens** [comment]
Hi,
No, this is not the problem. Even when it is another menu, with really existing pages, it's not working.
So, even when the second parent menu item ABOUT has a submenu, the ABOUT item doesn't work.

**Comment by Ataurr** [comment]
@amelsens open a ticket here with your details so we can take a look http://help.wpmet.com/

**Comment by xperter** [comment]
Remove this line, it will do the trick.
https://github.com/xpeedstudio/elementskit/blob/8cd6923db0cd216df03905dc6de54d33708210ae/widgets/nav-menu/assets/js/script.js#L27

**Comment by amelsens** [comment]
Hi,
Yes! Thanks, it works! ;-)
Maybe it should be a good idea to give administrators the choice if they want that parent menu items are also hyperlinks to pages or valid links or not. In fact giving them the choice to enable parent menu items to be used as links or disable it. So putting an extra parameter somewhere in the Elementor configuration of the Edit Nav menu Elementor widget. It's only a simple suggestion.
Anyway, I prefer to enable it.
Again, thank you so much to resolve this issue so fast! :-)
Best Regards and keep going the good works!

**Comment by amelsens** [comment]
Hi,

**Comment by amelsens** [comment]
Hi,
Now, I see why the parent menu items are not links for valid pages or links. 
Because in the responsive menu, the submenus aren't open by default. Users or visitors must first click on the parent menu items to open or roll down the submenus.
When I to the trick by removing the line 27 "e.preventDefault();" then in the responsive menu it's not possible anymore to use or clicking a submenu item. Because clicking on the parent menu items involve that the link will be active and close the menu.
Sorry, that I didn't check everything before I asked to solve an issue that wasn't a real problem at the beginning. 
Maybe it should be better that I reorganise my menu structure in the future so it will work as you have builded.
Anyway, I will considering this option lateron.
I only wanted to let you know what I my experiences were at this point.
Thanks again.
Best Regards.

**Comment by amelsens** [comment]
Hello,
I just want to let you know that I appreciate your efforts and that I appreciate your products, especially the great Header & Footer Builder for Elementor. This is great. This will change the way to build fast WordPress websites while respecting the owner's house style. Also the responsive menu is super great and easy to use.
As a way of appreciation and support, I bought the ElementsKit Pro this morning.
Especially the Header & Footer Builder for Elementor needs to be maintained or can certainly be extended. I will certainly continue to follow this up.
Congratulations with ElementsKit. Keep going up this great work! ;)
Best Regards,
Alain Melsens
