### ISSUE TITLE
How to change the Elementskit Header & Footer Nav Menu active Sub-menu item text & background color?

### ISSUE THREAD

**Issue by amelsens** [xpeedstudio/elementskit#3]
Hello,
![Elementskit-Nav-Menu-Active-SubMenu](https://user-images.githubusercontent.com/10380856/62469940-963d7480-b799-11e9-8b93-d347cf98b49d.jpg)
How can I change the active Submenu item text & background from the Nav Edit menu widget?
Now, the standard colors are deep blue for the background and black for the text. I want to change these colors but I can't find the settings in the widget setup panel. 
Or must I change this in a serated CSS file? Where can I find these CSS file?
I mean the text & background colors for the ACTIVATED submenu items.
Thanks in advance.
Best Regards.

**Comment by amelsens** [comment]
I will close this ticket here and continue with conversation on your other Support center.

**Comment by Ataurr** [comment]
Hi 
Sorry to say we have moved our support team here to our support desk. 
So we recommend contacting our team on our support desk...

For free version support: https://help.wpmet.com
Premium version support https://support.xpeedstudio.com/support-center/

**Comment by amelsens** [comment]
Hi,
Thanks for the information. I will keep it in mind.
Regards.
